PARTNER_ID=mpartner-default-resident,mpartner-default-abis,mpartner-default-esignet

ESIGNET_INSTANCE_1_PARTNERS=mpartner-default-esignet,partner2
ESIGNET_INSTANCE_2_PARTNERS=partner3
ESIGNET_INSTANCE_3_PARTNERS=partner4
ESIGNET_INSTANCE_4_PARTNERS=partner5

INJI_INSTANCE_1_PARTNERS=inji-1
INJI_INSTANCE_2_PARTNERS=inji-2