PARTNER_ID=mpartner-default-dvi1-mosipid

ESIGNET_INSTANCES={
    "esignet-mock": {
        "url": "esignet-mock.dev.mosip.net",
        "namespace": "esignet-mock",
        "deployment": "esignet-mock",
        "partners": ["esignet_mocknew1"]
    },
    
    "esignet-mosipid": {
        "url": "esignet-mosipid.dev.mosip.net",
        "namespace": "esignet-mosipid",
        "deployment": "esignet-mosipid",
        "partners": ["esignet_mocknew2"]
    }
}

INJI_INSTANCES={
    "mosipid-identity-usecase": {
        "url": "injicertify-mosipid.dev-int-inji.mosip.net",
        "namespace": "mosipid-identity-usecase",
        "deployment": "mosipid-identity-inji-certify",
        "partners": ["mpartner-default-dvi1-mosipid"]
    }
}
