PARTNER_ID=mpartner-default-abis,mpartner-default-digitalcard,mpartner-default-auth,mpartner-default-resident,mpartner-default-demo-oidc,mpartner-default-esignet,

ESIGNET_INSTANCES={"sunbird":{"url":"api-internal.sandbox.mosip.net","namespace":"esignet","deployment":"esignet","partners":["mpartner-default-esignet"]},"mock":{"url":"api-internal.sandbox.mosip.net","namespace":"esignet-mock","deployment":"esignet","partners":["partner3"]}}

INJI_INSTANCES={"certify":{"url":"api-internal.sandbox.mosip.net","namespace":"certify","deployment":"certify","partners":["mpartner-default-inji"]}}